server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:h2:file:~/demo/demo
    data-username: admin
    data-password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true

  freemarker:
    cache: false
    charset: CESU-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  path: ./logs