server:
  port: 8761
eureka:
  client:
    # 表示是否将自己注册到Eureka Server;默认为true。当前本身为Eureka Server，所以不需要注册
    register-with-eureka: false
    #是否从Eureka Server 获取注册信息，默认为true。单点Eureka不需要同步。如果为集群部署则需要从其他Eureka Servcer获取注册信息
    fetch-registry: false
    # 与Eureka Server 交互地址，查询服务和注册服务需以来此地址， 默认为：http://localhost:8761/eureka/
    # 集群Eureka Server 时可配置多个地址 用 ',' 分开即可
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    #开启基于HTTP basic的认证
    enabled: true
  user:
    name: eureka
    password: 123456
