server:
  port: 8000
#management:
#  security:
#    enabled: false #关掉安全认证
#  port: 8080 #管理端口调整成8088
#  context-path: /monitor #actuator的访问路径
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    data: classpath:data.sql
    schema: classpath:schema.sql
#    url: jdbc:h2:D:/H2DataBase/springtest
#    password: 123456
#    username: test
#    driver-class-name: org.h2.Driver
logging:
  level:
    ROOT: info
    org.hibernate: info
info:
    app:
      name: @project.artifactId@
      encoding: @project.build.sourceEncoding@
      java:
        source: ${java.runtime.version}
        target: @java.version@

